plugins {
    id 'java'
    id 'org.springframework.boot' version '2.7.4'
    id 'io.spring.dependency-management' version '1.1.4'
    id 'org.flywaydb.flyway' version '8.5.13'
    id 'io.freefair.aspectj.post-compile-weaving' version '8.6'
}

group = 'ru.mts'
version = '1.0-SNAPSHOT'

java {
    sourceCompatibility = "14"
}

repositories {
    mavenCentral()
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

compileTestJava.ajc.options.aspectpath.from = sourceSets.main.output
[compileJava, compileTestJava].each {
    it.ajc.options.compilerArgs += ['-xmlConfigured', "${projectDir}/src/main/resources/aop.xml"]
}


dependencies {
    implementation group: 'org.flywaydb', name: 'flyway-core', version: '8.5.13'
    implementation group: 'org.springframework.boot', name: 'spring-boot-starter', version: '2.7.4'
    implementation group: 'org.springframework.boot', name: 'spring-boot-starter-data-jpa', version: '2.7.4'
    implementation group: 'org.postgresql', name: 'postgresql', version: '42.7.3'

    implementation group: 'org.springframework.boot', name: 'spring-boot-starter-web', version: '2.7.4'
    implementation group: 'org.springframework.boot', name: 'spring-boot-starter-thymeleaf', version: '2.7.4'

    implementation group: 'org.springframework.boot', name: 'spring-boot-starter-validation', version: '2.7.4'

    implementation group: 'org.springframework.boot', name: 'spring-boot-starter-aop', version: '2.7.4'
    implementation group: 'ch.qos.logback', name: 'logback-core', version: '1.2.3'
    implementation group: 'org.slf4j', name: 'slf4j-api', version: '1.7.30'

    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.16.0'

    annotationProcessor("org.projectlombok:lombok:1.18.20")
    compileOnly("org.projectlombok:lombok:1.18.20")

    testImplementation 'org.springframework.boot:spring-boot-starter-test:2.5.0'
    testImplementation 'org.testcontainers:junit-jupiter:1.15.3'
    testImplementation group: 'org.junit.vintage', name: 'junit-vintage-engine', version: '5.10.2'
    testImplementation group: 'org.testcontainers', name: 'postgresql', version: '1.15.3'
    testImplementation group: 'org.testcontainers', name: 'testcontainers', version: '1.15.3'
    testImplementation group: 'ch.qos.logback', name: 'logback-classic', version: '1.2.3'

    implementation group: 'com.fasterxml.jackson.core', name: 'jackson-core', version: '2.16.0'
    implementation group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.16.0'
    implementation group: 'com.fasterxml.jackson.core', name: 'jackson-annotations', version: '2.16.0'
    implementation group: 'com.fasterxml.jackson.datatype', name: 'jackson-datatype-jsr310', version: '2.16.0'


    implementation project(':education-project-starter')

    implementation 'org.springframework.boot:spring-boot-autoconfigure:2.7.4'

}
tasks.named('test') {
    useJUnitPlatform()
}