animal.dog.names=buddy,max,rocky,lucky,barsik,persik,lola,lala,ivi,mimi
animal.shark.names=gurry,mikki,rax,katy,fil,tom,mopsy,tam,res,tutu
animal.wolf.names=wully,wally,bob,klay,grob,dag,klops,sweps,soh,pop

spring.datasource.url=jdbc:postgresql://localhost:5432/animals
spring.datasource.username=postgres
spring.datasource.password=minis123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.main.allow-bean-definition-overriding=true

spring.jpa.defer-datasource-initialization: true
