spring.datasource.url=jdbc:postgresql://localhost:5432/animals?currentSchema=animals
spring.datasource.username=postgres
spring.datasource.password=minis123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.main.allow-bean-definition-overriding=true

spring.jpa.defer-datasource-initialization: false
spring.jpa.hibernate.ddl-auto: validate

spring.flyway.user=postgres
spring.flyway.password=minis123
spring.flyway.default-schema=animals
spring.flyway.locations=classpath:/db/migration
spring.flyway.baselineOnMigrate = true