create schema animals;

CREATE TABLE IF NOT EXISTS animals.animal_type (
                                                   id_type INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                                   type VARCHAR(50) NOT NULL ,
    is_wild BOOLEAN NOT NULL
    );

CREATE TABLE IF NOT EXISTS animals.habitat (
                                               id_area INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                               area TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS animals.provider (
                                                id_provider INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                                name TEXT NOT NULL,
                                                phone VARCHAR(50) NOT NULL
    );

CREATE TABLE IF NOT EXISTS animals.animal (
                                              id_animal BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                              name TEXT NOT NULL ,
                                              id_type INTEGER NOT NULL references animals.animal_type(id_type) ON DELETE CASCADE,
    age SMALLINT NOT NULL
    );

CREATE TABLE IF NOT EXISTS animals.animal_habitats (
    id_animal_type INTEGER NOT NULL references animals.animal_type(id_type) ON DELETE CASCADE,
    id_area INTEGER NOT NULL references animals.habitat(id_area) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS animals.animal_provider (
    id_animal_type INTEGER NOT NULL references animals.animal_type(id_type) ON DELETE CASCADE,
    id_provider INTEGER NOT NULL references animals.provider(id_provider) ON DELETE CASCADE
    );

alter table animals.animal_habitats
    add constraint id_animal_type_area_pk
        primary key (id_animal_type, id_area);

alter table animals.animal_provider
    add constraint id_animal_type_provider_pk
        primary key (id_animal_type, id_provider);